### ISSUE TITLE
Demesne probleme

### ISSUE THREAD

**Issue by Zack7292** [Codasylph/Demesne#13]
idk why but when i try to make my demesne (by following your showcase) it never work even if i pu it into the exact block or anything, when i right click with my dowsing orb i was never able to actualy make the 4 stone bricks or the 4 temple marble and 4 gold bars, even in a lvl 8 zone wish is kinda anoying when i wanna start with your mod :/

if you want to know all the mods i was using for now im busy, jsut ask i'll give u it

**Comment by Zack7292** [comment]
i maybe have an idea for fixing this: beign able to crasft those in a crafting table with pretty mush a similar patern as block but well only be able to place them at the good spit refering to the douwsing orb as already but direcly without any transformation, if its not at the great spot, it say what ut say when u don't put it at a good spot

**Comment by Codasylph** [comment]
Most likely you are not placing all of the blocks in the correct location. The blocks need to be at the four center blocks of the chunk (horizontal center, vertical position can be whatever you like). The dowsing orb will indicate this to you by the blue orb in the center expanding when you are standing in a valid spot.  In the 1.12.2 version it should also tell you if you attempt to transform blocks that aren't positioned correctly, but I'm _assuming_ you're using the fabric version since your second comment seemed to be saying that that was not happening.

I recognize that the system for indicating a valid altar location is not the greatest, and I do intend to improve it in the future, possible with a HUD overlay or something, I will not be making the altar a place-able block as I like the aesthetics of the transformation.

Anyway, please make sure that the blocks are in the center of the chunk.  If need be a trick you can use is to go to the debug screen (by hitting f3) and check the line that says "Chunk," the first set of numbers give your block coordinates within a given chunk and those x and z coordinates will be 7s or 8s if you're in one of the center blocks. (ex. "Chunk: 7 14 8 in 26 0 89")
