### ISSUE TITLE
No lava tank?

### ISSUE THREAD

**Issue by JustJinxed** [Codasylph/Demesne#3]
Doesn't seem to be a lava tank in the 1.14.x Fabric version yet?

**Comment by Codasylph** [comment]
No, there is not. As of my writing this there is also no garden gnome, no shrinking potion effect, no temporal jars (because why would there be, there's no shrinking effect), no spirit lure, and probably some other things I'm not thinking of because that actually seems like a pretty short list and I can't possibly be doing that well.  It's not done yet.  There are also certain things that exist in one version that probably won't ever exist in some other versions, like I will probably never go back and add the forge or oven to the 1.12.2 version because there are so very many mods out for that version of Minecraft that cook things, and I probably won't add totem supports to the Fabric version because there are no obj models in the fabric version and totem supports exist purely to visually bridge the gap between an octagonal thing and a square thing.
All that said, you are at least the second person to reach out to me about the lava tank in particular, so I guess that feature is more appealing than I realized and I should get on that.   :)

**Comment by JustJinxed** [comment]
Even if you retire the lava tank to a config only option, it's very useful indeed! I love the aesthetic of the mod btw. I'm a big fan of any magic related mods in general. So to see you break in with something so noteworthy, I'm excited to say the least. 

Glad I asked Nightmare. You're not alone, as it seems a lot of devs are piece by piecing into Fabric this last update, and I thought for a moment that Fabric might be messing up / or something had gone wrong with the objects, but it's just the porting blues all around. (*sprinkles encouragement*) 

thanks for the reply btw :) Already a fan boy, but this was icing!

**Comment by JustJinxed** [comment]
(oh and closed so I don't mar your tracker with what should just be a possible upcoming feature ;)
