### ISSUE TITLE
Grinding Hopper and Cotton Resources Ore

### ISSUE THREAD

**Issue by JustJinxed** [Codasylph/Demesne#6]
Any chance you can add the ores from Cotton Resources (https://www.curseforge.com/minecraft/mc-mods/cotton-resources) to the Grinding hopper? At least Copper and Tin would be ideal on the 2x. You could totally RNG between 1-2 on the rest for scalability. Config would be most ideal, but I think I might be pushing it ;)

**Comment by Codasylph** [comment]
Hm. I wrote out a whole thing here, but then it occurred to me that I am the _only_ person who cares about the nitty gritty of my on-going internal debate on how integrated with Cotton Resources my mod should be.
So, here's the relevant bits: I would prefer my mod to be relatively consistent. In the case of the GH that means metal ore produces two dusts for ore doubling type purposes, and has a 50% chance of producing one side product which will probably be gravel, but might be something neat, like an extra dust for that metal or related metal or gem dust.  And, I think that's pretty normal for crushing machine type recipes.
In the case of my own mod I have a reasonable idea of what is "related" and also what actually exists and is used.  Unfortunately, between working on the various version of Demesne and my other mods, and my real life, I haven't had much of a chance to actually play minecraft in a while.  As a result, I have no freakin' clue what other mods are out for Fabric that use Cotton Resources and what materials they actually use and what their balance is like and although it's probably not a _huge_ deal because you have around a 5% chance of getting the related material as a side product, i don't want to step on other mod makers balance, or accidentally offer side products of metals that other mods might not actually be using and are therefore totally useless.
The GH also uses a json recipe. So, I'm pretty sure anyone could make a datapack to add to its recipes.
Now, all said (yes, this was the short version, I talk too much,) I would consider copper and maybe tin because those two are so darn ubiquitous throughout the history of minecraft tech mods that you would almost think they were vanilla materials, but at least for right now (i.e. until I'm more familiar with the fabric tech mod landscape, and it seems more stable), I'm not touching recipes for any other materials.

**Comment by JustJinxed** [comment]
Waiting is likely the best call, and I'm one of those that does like to hear about the internals, we are after all, on a github ;) Family of coders and all. 

Right now, the only ones who seem to use the extra resources are vivatech and materialization. I imagine it will broaden as soon as this forge/fabric battle dust settles, and/or more modders push onwards. If it's moddable in the json, that should be enough for cross compat. (*goes on a hunt*). The ores further on are worldgen rare enough to put in the imposition other mods might want out of it, but we'll see. If railtech, buildcraft, etc come out into fabric, that'd likely change quite a bit with excavation and the like.

**Comment by JustJinxed** [comment]
Ekk something happened with the 1.14.3-2.2.7 version and JMX. I ended up downloading JMX itself, and adding it to my mods, and it works fine. 

 java.lang.NoClassDefFoundError: grondag/fermion/shadow/jankson/Jankson
		at grondag.jmx.Configurator.<clinit>(Configurator.java:50)
		at grondag.jmx.JsonModelExtensions.onInitializeClient(JsonModelExtensions.java:40)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.lambda$logErrors$0(EntrypointUtils.java:38)
		at java.util.ArrayList.forEach(ArrayList.java:1257)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:36)

naughty imbeddeds always acting up! lol

**Comment by Codasylph** [comment]
Hm.  JMX wasn't supposed to be embedded at all. :/ I might have done something silly. Although, maybe JMX *should* be embedded.
